### ISSUE TITLE
Missing possibility to hide "content" tab

### ISSUE THREAD

**Issue by bartkummel** [bramley/phplist-plugin-contentareas#8]
Hi,

It would be nice if I could hide the "content" tab, since it is confusing for users, having two tabs where content can be edited.

Best regards,
Bart

**Comment by bramley** [comment]
You need to enter something on the Content tab because phplist validates that the content is not empty. But there isn't a way to hide a tab.

**Comment by bartkummel** [comment]
I am fully aware of that, and that is exactly my point: it is confusing to users. Wouldn't it be possible to fill the content area with some default content and hide the tab? And if that's really impossible, it would be really helpful to put some message at the top of the "content" tab, stating that content should be edited on the other tab.

**Comment by bramley** [comment]
You don't want to hide the Content tab because that is where you enter the subject and from address.
This plugin is not able to change what is displayed on the Content tab, such as displaying a warning.

It might be possible to populate the message content with some default text if the message content is empty, which would then avoid the phplist validation warning when submitting the campaign. But be aware that that text will appear in the final message, assuming that you have wrapped the [CONTENT] placeholder in an html comment.
